apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
  labels:
    app: web-server
spec:
  containers:
  - name: my-app-container
    image: nagamalleswarrao/xyztechnologies:2

---

apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: web-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer


